export const SET_A = [
  "jolt", "shade", "sill", "galt", "asp", "slat", "pestle", "must", "apron", "fall", "mull", "washer", 
  "fret", "acacia", "crate", "drill", "lam", "euphorb", "rattle", "earwig", "quid", "macaque", "nigella", 
  "rand", "coconut", "rack", "opal", "whip", "cutlass", "sambar", "skin", "junket", "fridge", "mole", "sled", 
  "packet", "grom", "tsuga", "smoke", "kiwi", "cymbals", "boiler", "turkey", "solanum", "chicory", "betta", 
  "shrub", "padlock", "nape", "chevrot", "quartz", "silk", "coco", "oilcan", "whistle", "bud", "kink", "ore", 
  "sequo", "kalong", "support", "cockpit", "echium", "wigeon", "yelp", "flip", "pista", "smear", "spar", 
  "zizania", "isatis", "king", "name", "shutter", "diadem", "milium", "saury", "lemming", "podium", "prunus", 
  "rate", "son", "drongo", "racoon", "grizzly", "surge", "dunlin", "timber", "beebalm", "gasket", "strap", 
  "vampire", "deer", "snow", "lily", "daphne", "cork", "branch", "wedge", "zinnia", "linden", "snaggle", "taut", 
  "mango", "dirt", "anchor", "orbit", "vault", "cytisus", "trim", "escolar", "rudd", "nail", "skylark", "castle", 
  "tree", "rush", "roar", "tapir", "prairie", "tilia", "sumac", "spin", "zone", "armeria", "cornus", "cowbird", 
  "amarant", "pilot", "lycoris", "soap", "linaria", "hemp", "blue", "piper", "draco", "ingot", "tulipa", "pace", 
  "swat", "oryza", "junk", "nasturt", "fine", "walrus", "peccary", "godwit", "bayou", "asarum", "heft", "nymph", 
  "hatch", "wand", "oil", "hazel", "disc", "jill", "bighorn", "orchid", "vriesea", "cockle", "coffea", "sou", 
  "tamarix", "ram", "track", "dace", "romneya", "jacket", "pave", "loft", "teleost", "coontie", "pupfish", "dugong", 
  "fox", "edge", "coot", "taxus", "betula", "uniola", "guanaco", "smart", "quince", "ledum", "volt", "box", "table", 
  "tamari", "kea", "hops", "lantana", "sponge", "album", "tune", "crinum", "basset", "gannet", "bog", "slop", "persim", 
  "rag", "cumin", "hotbed", "crocus", "apricot", "gram", "alfalfa", "dot", "wheal", "impala", "clipper", "ripe", 
  "quiver", "week", "dikdik", "urn", "saffron", "butter", "scab", "carton", "kind", "worm", "ewe", "ribes", "arum", 
  "conch", "saiga", "firecr", "effigy", "cassava", "dromaeo", "flier", "viper", "calffa", "typo", "fig", "cabbage", 
  "cabinet", "dark", "marjor", "hadock", "rent", "cornice", "diorama", "myrica", "soybean", "rum", "stud", "olive", 
  "foul", "fennel", "clover", "soft", "star", "leging", "leak", "limp", "seat", "quail", "caravel", "helm", "nick", 
  "elaeis", "catfish", "camel", "slog", "eyed", "lap", "chair", "thumb", "erica", "garment", "pottery", "casket", 
  "nyssa", "bank", "euryale", "kinglet", "gelding", "oar", "paper", "sand", "pier", "burbot", "flue", "quiz", "grating", 
  "manta", "mosq", "stone", "cherry", "croton", "trumpet", "float", "alcove", "day", "filly", "velum", "blotch", "tansy", 
  "wombat", "nozzle", "kilt", "walleye", "amulet", "wart", "collard", "joist", "tweezer", "razor", "robinia", "opaleye", 
  "kodu", "ragweed", "maiden", "yawn", "woodwar", "glycine", "tinsel", "reed", "chelone", "possum", "reseda", "stargaz", 
  "viscum", "pillar", "flicker", "tread", "layia", "rock", "water", "wind", "tidy", "oranger", "gasp", "duranta", "colt", 
  "hock", "hibisc", "poult", "sound", "transom", "tint", "waxwing", "drift", "derrick", "weal", "pitta", "hinge", 
  "adapter", "fuse", "clog", "spiraea", "tout", "bixa", "cisco", "dhole", "sunfl", "beetle", "glim", "photo", "davidia", 
  "hay", "grackle", "soot", "swop", "tag", "clout", "galleon", "omen", "nose", "tanger", "test", "womb", "coral", 
  "ling", "synbr", "wistari", "verge", "stipa", "codlet", "leer", "harpoon", "side", "fossa", "scag", "rye", "fire", 
  "curcuma", "pipe", "spear", "alembic", "kakapo", "linnaea", "walk", "pale", "yeast", "sauce", "phoenix", "spike", 
  "ocelot", "dock", "langur", "index", "fold", "siphon", "silo", "peony", "goldfin", "harrier", "worn", "chin", "whelp", 
  "crest", "scepter", "walnut", "snip", "burn", "hopper", "chamois", "wren", "magpie", "rampart", "medaka", "scud", 
  "shell", "flyer", "zenobia", "balcony", "willet", "creek", "suit", "chime", "shiner", "purse", "hail", "diascia", 
  "airship", "lacquer", "haul", "hydrant", "dolphin", "warbler", "mask", "petunia", "amsonia", "panther", "stooper", 
  "wit", "edel", "arrow", "mentha", "hyrax", "lamium", "ephedra", "chicken", "want", "rot", "soup", "oriole", "arch", 
  "mound", "prism", "onyx", "gorilla", "egret", "bittern", "mimulus", "humulus", "vitis", "boat", "pup", "faucet", 
  "grouse", "scull", "barrel", "meth", "kalmia", "opah", "wallaby", "slick", "garb", "chick", "polyp", "mode", "babaco", 
  "serval", "perch", "neat", "kite", "mitella", "snort", "osier", "buck", "gazania", "cuscuta", "cycad", "guff", "mule", 
  "okapi", "loon", "ruscus", "banana", "toad", "rorippa", "susan", "visor", "tent", "bean", "cost", "fennec", "lane", 
  "penguin", "face", "meadow", "tub", "dasheen", "tango", "hoheria", "bark", "keel", "redear", "fair", "shaft", "vicia", 
  "string", "dobson", "mute", "woe", "plywood", "garrupa", "odor", "page", "codiaea", "cereus", "goby", "poster", 
  "slender", "toe", "tope", "tact", "term", "cardam", "lent", "hound", "monal", "herb", "aconite", "look", "alarm", 
  "suni", "canary", "hook", "memo", "urutu", "corian", "wagg", "thuja", "mill", "pump", "leaf", "markhor", "saddle", 
  "lunaria", "cocos", "omnibus", "awning", "tour", "prop", "quad", "banksia", "square", "muzzle", "swab", "gores", 
  "flap", "guy", "spigot", "cleome", "pan", "watt", "bitch", "sieve", "bullet", "wood", "orca", "sloth", "fish", "relay", 
  "sorghum", "leek", "font", "baobab", "steppe", "pearl", "sphere", "wink", "dawn", "holcus", "jay", "mock", "jenny", 
  "radio", "lanyard", "slum", "crambe", "triton", "scirpus", "date", "carving", "yuhina", "caryota", "boot", "stag", 
  "wife", "genet", "redbird", "filter", "gyr", "valley", "puma", "magneto", "teem", "scow", "manakin", "bind", "indri", 
  "coast", "quohog", "croc", "daphnia", "gosling", "sit", "goral", "spring", "ouzel", "hollyh", "tons", "pure", 
  "opossum", "carica", "stoat", "dolly", "yuan", "part", "erineum", "rape", "bead", "adjuki", "mouth", "shamr", 
  "lithops", "zebra", "mark", "half", "mitre", "tuyere", "gerbil", "tatouay", "south", "wing", "punt", "alyssum", 
  "ballon", "steamer", "spindle", "kick", "forget", "view", "brick", "skua", "pouch", "console", "squash", "glove", 
  "merg", "stump", "serg", "fathead", "zucch", "clip", "veto", "knob", "troy", "winnow", "jetty", "poppy", "gourd", 
  "slim", "insect", "scar", "cliff", "guppy", "rare", "ruby", "pigeon", "locust", "madtom", "antenna", "map", "madder", 
  "gild", "horn", "tine", "lot", "smack", "taro", "shoe", "plum", "wheel", "bay", "loom", "snub", "high", "bistort", 
  "ibis", "placard", "senecio", "reticle", "dombeya", "silt", "pulp", "lance", "nettle", "tip", "ear", "pitcher", 
  "curtain", "allium", "mire", "javelin", "nave", "hickory", "joint", "axe", "maggot", "lip", "astilbe", "comb", "truss", 
  "walking", "scad", "daisy", "flange", "torenia", "atrium", "smite", "tack", "roll", "rang", "mussel", "rail", "armband", 
  "punch", "pulpit", "yot", "tug", "gladiol", "cog", "lint", "hutch", "tiger", "thaw", "gill", "knautia", "doze", "felt", 
  "tench", "furnace", "canyon", "periwin", "rifl", "groundh", "bellis", "pond", "borage", "capelin", "agama", "grate", 
  "viola", "dune", "quagga", "savory", "whet", "cobaea", "stilts", "grewia", "piwit", "soma", "battery", "frock", "crowbar", 
  "bow", "doe", "cricket", "moorhen", "tick", "sole", "clove", "race", "cucumb", "erodium", "carp", "cobra", "gould", 
  "gush", "east", "iris", "rasp", "john", "field", "huss", "rumex", "felicia", "wax", "tunnel", "bicycle", "bedbug", "husk", 
  "pony", "corm", "lump", "gout", "swan", "rheum", "ginkgo", "rhus", "pig", "drip", "fixture", "head", "hatchet", "poll", 
  "swam", "quay", "dew", "gueresa", "coyote", "fatsia", "iguana", "jet", "noose", "sandbag", "pass", "fur", "run", "bartsia", 
  "coin", "ambly", "corbel", "tile", "ball", "rug", "gang", "valve", "killie", "hilt", "altar", "capsule", "chard", "loot", 
  "shelter", "mantid", "girt", "violet", "foal", "whey", "donkey", "zip", "hunk", "bureau", "well", "otter", "tind", "icebox", 
  "barracu", "gander", "spoon", "cob", "abacus", "rapid", "shrimp", "mikania", "shim", "machete", "cage", "dogfish", "wive", 
  "ferry", "cloud", "mult", "snail", "gadwall", "discus", "chataho", "raccoon", "case", "piston", "oscar", "row", "flax", 
  "clue", "galega", "hem", "arnica", "kiln", "plain", "canna", "vulture", "bonsai", "tome", "cowslip", "gage", "abalone", 
  "form", "ledger", "myrtus", "cardoon", "torch", "risk", "rocket", "ton", "tech", "pike", "bisk", "journal", "ledge", "yort", 
  "camp", "lead", "pimento", "jaguar", "span", "marmot", "four", "buckle", "facade", "way", "larix", "prawn", "rotor", "gibbon", 
  "hummer", "aorta", "spud", "tang", "grille", "fact", "thicket", "blender", "molinia", "opt", "zostera", "circuit", "monkey", 
  "hebe", "rubus", "plaque", "wafer", "pot", "bitter", "cygnet", "oniscos", "dory", "jelly", "boulder", "hen", "eruca", "ape", 
  "cougar", "reel", "gape", "ginger", "yell", "bellows", "cudgel", "grove", "clay", "pothos", "tie", "vinegar", "lilac", "lust", 
  "spine", "napkin", "bobbin", "song", "thistle", "nut", "halibut", "elymus", "dogwood", "pituoph", "esox", "newt", "seep", 
  "fort", "stripe", "sip"
];

export const SET_B = [
  "liatris", "parsley", "towel", "pratia", "pill", "freckle", "gudgeon", "peat", "lord", "toona", "hawser", "rout", "halo", 
  "cattail", "gulf", "mist", "sardine", "hippo", "emu", "wove", "periw", "coffin", "sink", "poplar", "shack", "wham", "lever", 
  "haven", "cross", "nandu", "elem", "ermine", "frigate", "rip", "sophora", "glut", "eye", "mullet", "sect", "sequoia", "picea", 
  "logbook", "hoe", "curl", "cheetah", "rowan", "neap", "sulf", "numbat", "jasmine", "drag", "aster", "till", "toy", "sea", 
  "pylon", "tulip", "veranda", "tarp", "quercus", "rubble", "skit", "cape", "telekia", "onion", "join", "stencil", "juncus", 
  "toga", "lindera", "clock", "sculpin", "syringa", "mimosa", "jig", "tusk", "shoat", "auk", "gust", "reef", "luzula", "hood", 
  "line", "chimp", "pick", "lag", "etching", "door", "flag", "bichir", "hare", "target", "piranha", "bracket", "skink", "xenops", 
  "cowrie", "muscari", "tan", "hunt", "bison", "atap", "towhee", "sallow", "logan", "beaver", "pool", "toucan", "yam", "salad", 
  "gravel", "poa", "antler", "pest", "tass", "pole", "caiman", "lapsana", "mucus", "green", "cusk", "canvas", "jujube", "sofa", 
  "top", "silver", "pupa", "chalk", "riot", "lath", "filbert", "areca", "gate", "spoor", "potto", "lobster", "stub", "mine", 
  "bloom", "lycium", "hoop", "termite", "bream", "armad", "fiddler", "ash", "pail", "dyke", "scoter", "cuphea", "gator", "chisel", 
  "blackb", "mind", "mangrov", "epaulet", "grain", "toast", "glen", "pisum", "mink", "flask", "rue", "yurt", "coop", "cruet", 
  "rigging", "reach", "gaura", "slit", "writ", "lupinus", "team", "pea", "toot", "pleione", "bee", "deutzia", "keen", "tern", 
  "lythrum", "parrot", "bold", "west", "wasp", "wear", "tupelo", "aoudad", "finger", "dust", "cosmos", "log", "ocean", "zinc", 
  "avena", "flower", "scan", "halt", "toil", "flute", "endivia", "open", "sedge", "mailbox", "iresine", "quarry", "papaya", 
  "sheath", "urena", "knocker", "spatula", "nardus", "coir", "mustard", "yard", "gimp", "crutch", "bar", "stove", "jackal", 
  "mayfly", "llama", "buzzard", "sycamor", "trap", "alpaca", "whoa", "maackia", "gull", "sunfish", "roller", "keg", "ruff", 
  "carnat", "tamarin", "verbena", "magnol", "clew", "phlomis", "impalas", "glue", "scup", "vile", "shin", "coix", "carex", 
  "birk", "moray", "banyan", "nandina", "kelt", "base", "goggles", "wildeb", "tallow", "pecan", "cabana", "neem", "setaria", 
  "fiber", "snake", "vow", "tower", "zipper", "fantail", "angora", "quote", "scampi", "basking", "bryony", "ivy", "takahe", 
  "saguaro", "cool", "beet", "jean", "ensign", "gash", "note", "lathe", "hearth", "damper", "mistle", "serin", "cane", "web", 
  "gloom", "fender", "scraper", "gar", "spruce", "plate", "brush", "hod", "puffer", "smelt", "solar", "salvia", "globba", 
  "slip", "fawn", "mud", "fulmar", "tom", "channel", "brooch", "thimble", "dial", "frog", "skid", "mosaic", "shield", "scat", 
  "bramble", "vigna", "boar", "whiz", "tuck", "cable", "rice", "blazer", "opuntia", "kob", "pacu", "bag", "ostrich", "runt", 
  "crystal", "sprat", "scilla", "kagu", "cress", "crow", "pencil", "bowfin", "rant", "harness", "cater", "elver", "oak", "forest", 
  "wrench", "crown", "thread", "stachys", "stint", "leopard", "jack", "coffer", "lard", "snob", "range", "rhea", "veldt", 
  "celosia", "spur", "thrush", "pen", "rung", "trench", "weft", "wort", "lurk", "piano", "bident", "sloe", "latch", "chute", 
  "grape", "halenia", "bluet", "turnera", "catalpa", "dove", "hakea", "mint", "ceiba", "trig", "grot", "scythe", "daucus", 
  "shoal", "urchin", "garlic", "tuba", "genista", "deck", "counter", "bokchoy", "lapel", "veal", "samosa", "zing", "leap", 
  "lantern", "cuirass", "lark", "road", "mamba", "pneappl", "pinto", "hydra", "tomb", "ferula", "dent", "ted", "caltrop", 
  "barbel", "guitar", "trio", "cnicus", "fresh", "cicada", "globe", "lewisia", "viaduct", "robe", "chervil", "loose", "wahoo", 
  "snipe", "silene", "cyathea", "bat", "wildcat", "surf", "jackdaw", "coal", "tuft", "spire", "flare", "bright", "winch", "rein", 
  "trout", "phial", "heap", "tell", "portico", "tobacco", "nutria", "scalpel", "slipper", "squid", "cran", "bloc", "ostrya", 
  "ware", "emperor", "swob", "azalea", "rhod", "crop", "dump", "loam", "knit", "duiker", "rote", "pieris", "dodo", "bowl", 
  "salix", "morus", "kumquat", "huchen", "jam", "olingo", "lava", "ooze", "jockey", "glowfly", "cedar", "yapok", "garrya", 
  "crappie", "glider", "slew", "arbutus", "reactor", "toke", "chinch", "taper", "cord", "breeze", "marble", "tart", "passion", 
  "geum", "jest", "dry", "harp", "mirror", "jigsaw", "rib", "hammock", "dipper", "rear", "ilex", "otocin", "silvers", "tite", 
  "launch", "piglet", "carbine", "bill", "wagtail", "grotto", "hosta", "user", "gloss", "quill", "item", "thorn", "typha", 
  "leech", "link", "yett", "grommet", "cloak", "pimenta", "wrasse", "bolster", "shuttle", "vein", "scam", "linum", "sway", 
  "tank", "brant", "vase", "warp", "vigil", "bongo", "bale", "wain", "escario", "foot", "fiddle", "swamp", "sham", "back", 
  "veer", "zero", "mat", "cave", "skunk", "haft", "cuckoo", "crypt", "badge", "woad", "kestrel", "gazelle", "soy", "graft", 
  "cydonia", "via", "coleus", "trip", "barb", "talc", "rosary", "sleeper", "cubicle", "saber", "pennant", "caracal", "drosera", 
  "wild", "beagle", "film", "handbag", "nene", "path", "emblem", "them", "vortex", "poker", "ream", "muffler", "plug", "wisp", 
  "kimono", "oath", "spit", "book", "ficaria", "sire", "gentian", "fern", "cell", "skimmer", "dam", "db", "haddock", "gall", 
  "hour", "hump", "archway", "hide", "cirsium", "glass", "flint", "pair", "cypress", "hagfish", "wont", "gerani", "mere", 
  "avocado", "pikemin", "vat", "platy", "ride", "magnet", "bell", "coati", "louver", "rust", "raisin", "blenny", "roof", 
  "hake", "compass", "lupine", "merlin", "what", "gibb", "eucomis", "scooter", "drimys", "mast", "rule", "burdock", "vanilla", 
  "flycat", "cinnam", "hint", "smolt", "cercis", "cube", "pear", "bough", "band", "gump", "label", "mamushi", "mush", "linsang", 
  "motor", "juglans", "winter", "tundra", "verse", "text", "vibe", "onosma", "shallow", "ribbon", "cooler", "yak", "copal", 
  "wheat", "solit", "siamang", "sensor", "duct", "hag", "jaw", "wagon", "stall", "spool", "moat", "spider", "oribi", "turnip", 
  "nectar", "teal", "zast", "pentas", "sedan", "hemlock", "herring", "talinum", "gain", "sesame", "salmon", "ruellia", "rope", 
  "set", "stevia", "antlion", "noddy", "tomtit", "apple", "tool", "waist", "rod", "sabal", "whin", "haze", "buss", "diploma", 
  "sick", "shot", "joey", "rap", "noddies", "belt", "citron", "gecko", "bamboo", "vervet", "with", "tire", "candle", "daylily", 
  "sir", "gupy", "panda", "perk", "osprey", "ense", "anoa", "tardis", "sedum", "corylus", "ocarina", "hack", "coptis", "tadpole", 
  "levy", "oxalis", "vote", "fabric", "privet", "rudder", "halberd", "weevil", "cock", "dingo", "lid", "knack", "lychee", "stob", 
  "draft", "aphid", "peacock", "root", "rainbow", "gnu", "sconce", "tar", "heart", "cocoa", "mouflon", "sagina", "maize", "fir", 
  "osmunda", "slur", "beech", "spot", "stork", "avocet", "steel", "trident", "gongora", "itea", "wake", "omul", "snoek", "aspen", 
  "koala", "parr", "mahogan", "char", "lyre", "monarch", "ringlet", "damp", "redwood", "bantam", "pygmy", "plumb", "nest", "ox", 
  "past", "file", "ferret", "juniper", "yaqui", "clod", "homeria", "tagetes", "vessel", "dirk", "least", "fry", "aloe", "vest", 
  "rhino", "ipomoea", "foxglov", "radar", "rosa", "wattled", "lock", "fly", "cocteau", "wire", "hamster", "zeal", "rink", "sum", 
  "guava", "maple", "robin", "mouse", "seagull", "boldo", "lac", "boxwood", "whir", "vixen", "yowl", "ant", "grebe", "tear", 
  "budgie", "dreamer", "succisa", "xiphias", "cask", "needle", "tit", "yew", "jersey", "bridle", "ruin", "lung", "rim", "skimmia", 
  "lyonia", "hall", "lychnis", "litchi", "pavia", "pontoon", "diary", "wad", "redpoll", "cup", "slid", "heron", "lime", "lintel", 
  "mare", "johnny", "muff", "red", "condor", "tops", "soil", "mantel", "unit", "thin", "tecoma", "clary", "pointer", "bullace", 
  "pyramid", "jessam", "mailbag", "populus", "willow", "macaw", "narrow", "horse", "halales", "bugloss", "zander", "cassia", "shrew", 
  "heather", "bond", "pomeg", "hubcap", "skirt", "pelt", "murre", "candytu", "exhaust", "swift", "club", "flora", "blesbok", "type", 
  "cynara", "tibia", "cap", "slab", "north", "funkia", "gut", "gunboat", "bolt", "rill", "lilium", "turn", "nerine", "puku", "frost", 
  "hoof", "garial", "tarrag", "yarn", "mount", "bunk", "tuna", "clasp", "wreath", "papyrus", "dish", "not", "moon", "crib", "basin", 
  "soak", "engine", "takin", "shut", "pisonia", "monarda", "air", "narciss", "stapler", "whelm", "easel", "tiki", "jasione", "shore", 
  "sift", "siskin", "hat", "snowdr", "desk", "jog", "blade", "crank", "sledge", "lawn", "wharf", "gore", "yield", "echidna", "oregano", 
  "rafter", "clethra", "sage", "mote", "peer", "larva", "tractor", "shard", "hair", "batata", "duck", "finch", "calla", "frame", 
  "swig", "foam", "weigela", "dill", "kudu", "manioc", "laurus", "emery", "vicuna", "lobelia", "voce", "mynah", "trogon", "damson", 
  "pageant", "turk", "gold", "navy", "shale", "aye", "trestle", "viburn", "grid", "foxface", "madia", "drum", "phleum", "siren", "coaster"
];

export const SET_C = [
  "rig", "coil", "pepper", "collage", "goat", "pin", "spun", "shag", "rite", "acorn", "levee", "orb", "river", "hot", "comfrey", 
  "caboose", "cucumis", "eraser", "rivet", "kunzea", "zest", "guille", "teak", "nudge", "pagoda", "serf", "atropa", "lair", "wolf", 
  "gambus", "snuff", "dorado", "paris", "grim", "jingle", "queen", "twig", "vial", "left", "ide", "spoke", "knuckle", "mesh", 
  "nerite", "calm", "two", "tulwar", "pine", "clear", "void", "manhole", "throne", "basket", "gurnard", "cotinus", "tee", "brazier", 
  "hob", "speaker", "puffin", "hydran", "tilt", "holster", "decoder", "lion", "swag", "lunt", "wool", "nepeta", "saw", "sable", 
  "scarf", "wipe", "loquat", "wels", "tiercel", "trinket", "basil", "quota", "card", "smit", "lynx", "ashcan", "wall", "manihot", 
  "western", "wig", "spark", "vole", "record", "monk", "tyre", "skew", "violin", "palette", "chiff", "bulrush", "cordage", "loaf", 
  "lean", "joke", "almond", "chest", "kid", "dronte", "creeper", "salt", "lack", "shark", "vireo", "argali", "halter", "tolmiea", 
  "tong", "firebox", "tail", "spinach", "fan", "redeye", "soda", "dowel", "mop", "sock", "styrax", "durian", "jumper", "roan", 
  "igniter", "prow", "calf", "jerboa", "shama", "curlew", "tutu", "holly", "rift", "ship", "sheld", "yoke", "bunting", "golden", 
  "strut", "bug", "knee", "loch", "depot", "puchera", "chives", "coax", "nuphar", "hoya", "pika", "tump", "blanket", "dryas", "seed", 
  "cotton", "palm", "warm", "paca", "lolium", "column", "tetra", "sorbus", "jewel", "quoit", "stonech", "fin", "dagger", "weak", 
  "sluice", "chalc", "nyala", "lycopus", "wean", "paint", "toolbox", "marten", "post", "trow", "stick", "aralia", "tessell", "iron", 
  "turret", "manatee", "endive", "screen", "deep", "dandel", "rest", "blimp", "weld", "spray", "olearia", "word", "swap", "tinamou", 
  "burlap", "grass", "nelumbo", "atoll", "rifle", "strait", "columb", "bunt", "bobcat", "whinch", "sparrow", "dray", "argenti", 
  "krait", "krill", "caraway", "slag", "slug", "snap", "knife", "drake", "moa", "flea", "cleat", "tarpon", "musket", "isle", "rook", 
  "rind", "caddis", "dog", "anethum", "melissa", "spade", "owl", "ladder", "scale", "kerf", "whiting", "conger", "cowfish", "delta", 
  "gopher", "pocket", "ottoman", "gun", "pack", "fork", "trod", "kern", "yore", "ring", "gondola", "potato", "socket", "boneset", 
  "fuchsia", "year", "ixia", "scaup", "tape", "ramonda", "eucalyp", "ballot", "sky", "dassie", "brier", "skillet", "numb", "torn", 
  "moth", "longear", "anise", "rooster", "rick", "minnow", "carpet", "couch", "statue", "neck", "oat", "vane", "stylus", "bucket", 
  "gallows", "ruler", "weight", "bottle", "feather", "anemone", "plow", "moneses", "lamp", "citrus", "ladybug", "rub", "peanut", 
  "crook", "summer", "badger", "rasbora", "booklet", "kin", "foil", "veery", "lettuce", "fang", "rabbit", "pain", "slate", "tarsier", 
  "hard", "quoin", "hive", "pellaea", "welt", "sump", "mould", "paw", "lens", "edifice", "wile", "norm", "octopus", "tame", "tin", 
  "low", "net", "horneth", "bone", "clarkia", "lad", "baboon", "hyssop", "light", "shun", "whig", "chock", "chough", "chat", "perilla", 
  "archer", "bluethr", "eider", "cone", "ford", "celery", "abelia", "cow", "trapa", "seal", "nerium", "taipan", "mahonia", "trepan", 
  "zebu", "baton", "nemesia", "larch", "tube", "rotifer", "zither", "clam", "miss", "brotula", "wrap", "tahr", "hill", "mantle", 
  "fetters", "hasp", "steer", "ulmus", "blow", "midge", "girdle", "snare", "medusa", "rank", "luggage", "lotus", "sign", "gavial", 
  "maul", "thyme", "grip", "firefly", "salsify", "pink", "briar", "slam", "yolk", "bronze", "facet", "marquee", "cushion", "button", 
  "beam", "turbot", "chub", "cicer", "ward", "rhamnus", "cholla", "roam", "thing", "eel", "obelisk", "urginea", "marigol", "relic", 
  "shed", "wasabi", "bleak", "buffalo", "elm", "canteen", "eustoma", "scallop", "elder", "pillow", "dredge", "rat", "surgeon", 
  "ononis", "malva", "maypole", "par", "spout", "watch", "cory", "mug", "elixir", "tomato", "wattles", "rhubarb", "dragon", "myrtle", 
  "oryx", "dusk", "gila", "rose", "gird", "gulper", "lute", "stem", "tier", "stock", "vet", "phlox", "lemon", "wade", "crane", 
  "goldcr", "flank", "nolina", "millet", "tarn", "cresset", "mallard", "bulb", "sheep", "smilax", "sort", "yucca", "arowana", 
  "blossom", "meerkat", "less", "tally", "booby", "duffel", "stamp", "ginseng", "celtis", "agave", "clap", "noon", "sander", 
  "torpedo", "plant", "dwarf", "zoom", "platty", "swallow", "port", "bluesp", "slot", "sago", "sailfin", "draba", "arbor", 
  "picture", "punk", "carissa", "mortar", "sika", "barley", "weather", "plover", "pad", "zorilla", "ixora", "malus", "host", "skate", 
  "vice", "limpkin", "moho", "hornet", "sawfly", "seam", "boss", "fisher", "trophy", "spotted", "civet", "yarrow", "flow", "parsnip", 
  "loop", "shovel", "danio", "carrot", "lace", "cactus", "pumpkin", "lagurus", "asimina", "chayote", "rain", "weir", "hull", "inlet", 
  "sew", "nook", "sprout", "shackle", "conifer", "elk", "lapwing", "chamo", "gourami", "mulber", "currant", "gallery", "hypoxis", 
  "wim", "cashew", "wine", "ramp", "galley", "hip", "flaw", "splint", "snout", "borer", "kit", "cod", "laurel", "primr", "visa", 
  "jacana", "lure", "hulk", "tellima", "desert", "vent", "pet", "stye", "rove", "caribou", "flock", "tare", "mold", "trellis", 
  "tripod", "brim", "wet", "ray", "pelican", "wold", "helmet", "jail", "bull", "drab", "tup", "burner", "stot", "gilt", "narwhal", 
  "load", "copper", "sharp", "panax", "flat", "stow", "mum", "safe", "scuttle", "beret", "tow", "inula", "sail", "liriope", 
  "sword", "weed", "sash", "list", "reap", "molly", "vise", "ebony", "grenad", "melon", "poncho", "saucer", "capy", "shop", 
  "quoll", "crepis", "ivory", "straw", "hawk", "cavy", "wide", "canola", "cupola", "mastiff", "sard", "jar", "rely", "betony", 
  "step", "snag", "beaker", "loan", "pipit", "grouper", "goar", "elodea", "anole", "snorkel", "darter", "clapper", "clivia", 
  "caper", "blurry", "mussell", "mite", "birch", "twit", "azara", "weasel", "loss", "kettle", "kitbag", "darmera", "spec", "woke", 
  "panel", "moose", "nutmeg", "datura", "castor", "gear", "silybum", "inkwell", "bend", "skirret", "buoy", "camphor", "incline", 
  "louse", "girder", "tamp", "aucuba", "barbet", "amber", "lake", "rut", "raft", "tale", "truck", "pod", "armor", "punica", 
  "orchis", "persea", "polecat", "oyster", "planer", "myrrhis", "chain", "rise", "room", "hyacint", "kept", "rave", "cook", 
  "bear", "coffee", "carya", "ia", "coat", "weta", "sorrel", "sleeve", "mallow", "eugenia", "tide", "shadow", "wether", "grit", 
  "smug", "dahlia", "croaker", "kudzu", "slough", "zenaida", "sun", "fast", "zelkova", "paeonia", "chive", "brace", "peel", 
  "isopod", "junco", "whelk", "fag", "moss", "arm", "alkanet", "thong", "peach", "site", "primula", "olea", "fog", "island", 
  "buxus", "night", "shod", "cistus", "viol", "cay", "wick", "heel", "verb", "batfish", "claw", "sap", "spew", "hyena", "muse", 
  "pickaxe", "hand", "chiton", "runner", "sore", "sing", "banner", "milla", "hordeum", "adder", "netting", "rake", "ice", "hoopoe", 
  "gorge", "raven", "kip", "whim", "turf", "ani", "rosemar", "work", "galium", "scot", "hedera", "sour", "burnet", "berry", "radish", 
  "coypu", "folder", "fruit", "cyperus", "festuca", "need", "ricinus", "python", "dunnock", "redwing", "fallow", "gong", "drop", 
  "kitten", "burr", "bustard", "caecil", "gray", "eland", "pile", "waif", "vinca", "stave", "marker", "eastern", "trolley", "skiff", 
  "block", "reek", "leg", "pollock", "tink", "skipper", "kerria", "win", "tore", "hind", "giraffe", "jade", "rump", "anchovy", 
  "tunica", "bassoon", "unicorn", "key", "mural", "rood", "panicum", "bits", "slob", "loris", "pinion", "brass", "marsh", "lemur", 
  "dart", "darn", "gauge", "cormo", "goose", "show", "shears", "shoot", "wringer", "tautog", "wend", "bandana", "calk", "land", 
  "redline", "skim", "wift", "urtica", "sol", "stod", "kokanee", "paddle", "cleaver", "coca", "freesia", "lizard", "lattice", "park", 
  "sextant", "ibex", "skip", "samba", "pumpk", "patch", "burl", "sprit", "marlin", "apios", "black", "wane", "tea", "jug", "pawn", 
  "sickle", "slow", "bridge", "rich", "peck", "tanager", "cove", "curd", "neon", "lift", "wavy", "cuscus", "angler", "sow", "pleco", 
  "gale", "torreya", "ruta", "pane", "hammer", "jot", "hoard", "toll", "te", "corset", "nerve", "retort", "knot", "bettas", "alder", 
  "lentil", "swot", "vine", "lamb", "task", "agouti", "rhexia", "kelp", "scum", "press", "stog", "orange", "wave", "scoop", "job", 
  "gutter", "fagus", "tram", "roanoke", "wash", "yeti", "illium", "lamprey", "shelf", "use", "oilbird", "cichlid", "cart", "amaryll", 
  "okra", "ficus", "topaz", "clamp", "butt", "jambos", "whale", "brook", "weep", "coastal", "moorish", "laelia", "cold", "pyrus", 
  "evergl", "falcon", "quip", "sinker", "trot", "pulley", "bass", "petrel", "tassel", "corn", "town", "weaver", "gorget", "bush", 
  "cat", "calluna", "thymus", "soar", "balsam", "sweet", "yea", "muntjac", "gem", "corvina", "chalice", "fumaric", "anvil", "shrike", 
  "tone", "tilapia", "diesel", "peep", "lactuca", "hose", "shako", "beak", "dome", "peg", "kale", "buff", "bagpipe", "maranta", 
  "locket", "melia", "puppet", "ridge"
];


function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function shuffle(arr) {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

export function generatePhrase() {
  const words = shuffle([pickRandom(SET_A), pickRandom(SET_B), pickRandom(SET_C)]);
  return words.join("-");
}

export function normalizePhrase(parts) {
  return parts
    .map((p) => String(p || "").trim().toLowerCase().replace(/[^a-z]/g, ""))
    .join("-");
}
